app:
  always_on_top: false
  auto_start: false
  debug: false
  first_run: true
  minimize_to_tray: true
  name: Gaming Helper Overlay
  theme: dark
  transparency_enabled: true
  version: 1.0.0
control_panel:
  always_on_top: false
  auto_hide: false
  opacity: 0.95
  position:
    x: 200
    y: 200
  remember_position: true
  size:
    height: 600
    width: 800
floating_icon:
  always_on_top: true
  draggable: true
  enabled: true
  icon_path: assets/icons/app_icon.png
  opacity: 0.8980392156862745
  position:
    x: 3
    y: 783
  size:
    height: 50
    width: 50
hotkeys:
  emergency_hide: Ctrl+Shift+H
  toggle_all_panels: Ctrl+Shift+A
  toggle_control_panel: Ctrl+Shift+G
performance:
  fps_limit: 60
  low_cpu_mode: false
  max_threads: 10
  memory_limit_mb: 500
plugins:
  auto_load: true
  check_updates: true
  enabled:
  - anti-afk_emulation
ui:
  always_on_top: true
  animations: true
  blur_background: true
  border_color: '#3498db'
  border_width: 2
  custom_borders: true
  glass_effect: true
  opacity: 0.9
  smooth_transitions: true
  theme: auto
