app:
  always_on_top: false
  auto_start: false
  check_updates: true
  first_run: true
  language: es
  minimize_to_tray: true
  name: Gaming Helper Overlay
  startup_delay: 2.0
  theme: dark
  transparency_enabled: true
  version: 1.0.0
control_panel:
  always_on_top: false
  auto_hide: false
  opacity: 0.95
  position:
    x: 200
    y: 200
  remember_position: true
  size:
    height: 600
    width: 800
floating_icon:
  always_on_top: true
  draggable: true
  icon_path: assets/icons/app_icon.png
  opacity: 1.0
  position:
    x: 1811
    y: 910
  size:
    height: 50
    width: 50
hotkeys:
  emergency_hide: Ctrl+Shift+H
  toggle_all_panels: Ctrl+Shift+A
  toggle_control_panel: Ctrl+Shift+G
keybinds:
  emergency_hide: Ctrl+Shift+H
  low_cpu_mode: false
  memory_limit_mb: 500
  toggle_control_panel: Ctrl+Shift+C
  toggle_overlay: Ctrl+Shift+O
logging:
  backup_count: 5
  level: INFO
  log_to_console: false
  log_to_file: true
  max_file_size: 10MB
main_window:
  maximized: false
  position:
    x: 300
    y: 300
  size:
    height: 400
    width: 500
performance:
  fps_limit: 60
  low_cpu_mode: true
  max_threads: 10
  memory_limit: 512
  memory_limit_mb: 500
  thread_pool_size: 4
plugins:
  auto_discover: true
  auto_load: true
  check_updates: true
  enabled:
  - multi-hotkey_macros
ui:
  always_on_top: false
  animations: true
  blur_background: true
  border_color: '#3498db'
  border_width: 2
  custom_borders: true
  font_family: Segoe UI
  font_size: 12
  glass_effect: true
  smooth_transitions: true
  theme: light
  transparency_enabled: true
